### PR TITLE
Server option

### PR DESCRIPTION
**Pull request by jtommi**
Linked to issues [4](https://github.com/MacroPower/macropower-analytics-panel/issues/4) and [10](https://github.com/MacroPower/macropower-analytics-panel/issues/10).

I added an option called "Server type" which let's you choose between Telegraf and Custom.
If you choose Custom, the No cors option disappears.
In getRequestInit it sets no cors to false if the server type is custom
https://github.com/jtommi/macropower-analytics-panel/blob/087597e6ca8dbf982e27796fe812ae414e2f34ca/src/AnalyticsPanel.tsx#L65

WDYT?

### CODE REVIEW

**Comment by MacroPower** [comment]
Hey, thanks for the PR. 🙂  So I really like the idea of preventing settings where users are guaranteed to run into a problem, it definitely makes sense. However, I think this isn't the best way to go about it. Mainly because there _are_ use-cases (albeit edge cases) where you might want to create your own http listener, and for one reason or another (security etc) you can't use CORS. As you yourself saw, outbound requests will still work properly with no-cors, you just can't receive a response back.

However, what would make sense in my opinion is to disable the option to disable cors if `Post end` is enabled. Because `Post end`, regardless of whatever your circumstances are, will _never_ work without CORS being enabled, because it requires the listener to reply with an id object.

I think that, ideally, enabling `Post end` would toggle `No cors` to false (internally), and then hide the switch. Likewise, disabling `Post end` would make `No cors` visible again, and keep its previous value. So, very similar to what you did, but without the extra option.

Also should maybe improve the description on those options a bit to better explain what's going on, so people don't get too confused as to why that option goes away.

Let me know what you think about that. And feel free to use this PR (rebase or w/e) if you agree and want to give it a shot. I squash and merge so no worries on history.

**Comment by jtommi** [comment]
Sounds good.
The Readme should maybe also address the Access-Control-Allow-Origin header for people like me that have a vague understanding of a lot of things but a deep understanding of few things :)

**Comment by jtommi** [comment]
In a [comment](https://github.com/MacroPower/macropower-analytics-panel/issues/4#issuecomment-658395927) you mentioned that you added "No CORS" for use with Telegraf and that there an opaque response is fine.
So in case a Telegraf server is used, shouldn't the option be available even if Post end is true ?
If that's the case, the server type option would still be needed.
So that's what I adapted. Let me know what you think.
I also took a few minutes to set up my environment to be able to easily build and test

**Comment by MacroPower** [comment]
So you're right, there are probably use-cases for Post-end without CORS. It doesn't make sense for a lot of the telegraf outputs, but for some of them (e.g. basically anything that's not a tsdb), it does.

The thing is that the plugin still expects a `{location: x}` response. And this will *never* work without CORS, because the server *must* be able to send a response body. So something like what you have in your PR could still break depending on the circumstances.

You could argue that this was actually just a bad design choice, and at this point I would actually agree with that. If we simply did something like discussed in #12 , a property to denote the nature of the request, in combination with a GUID to identify the session, it actually wouldn't be required at all. We could actually just use No-cors for any request, and it wouldn't matter one way or another. The option could be removed entirely, and things would always "just work".

And if that was changed, it might honestly present a good opportunity to add a proper backend service to the repo that implemented this and exported the actual session length to Prometheus or some other tsdb.

**Comment by MacroPower** [comment]
@jtommi I had some time so I took a stab at implementing what I was talking about in #13 - feel free to give it a look

**Pull request closed without merging**
